# Generated by Django 5.0.3 on 2024-04-30 19:59

import django.core.validators
import django.db.models.deletion
import login.models.custom
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Must be at least 2 characters.'), django.core.validators.MaxLengthValidator(limit_value=50, message='Must not exceed 100 characters.')])),
                ('description', models.CharField(blank=True, max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Must be at least 5 characters.'), django.core.validators.MaxLengthValidator(limit_value=250, message='Must not exceed 250 characters.')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Positive number required.')])),
                ('type', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be: 0 (Deposit) or 1 (Withdrawal)'), django.core.validators.MaxValueValidator(limit_value=1, message='Value must be: 0 (Deposit) or 1 (Withdrawal)')])),
                ('spend_date', login.models.custom.CustomDateTimeField()),
                ('date_created', login.models.custom.CustomDateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='dashboard.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='login.user')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'db_table': 'expense_expenses',
            },
        ),
    ]
